[monitoring]
monitoring-server ansible_host=<PRIVATE_IP>

[monitoring:vars]
ansible_user=ubuntu
storage_setup_enabled=true
# Bastion 경유 접속
ansible_ssh_common_args='-o ProxyJump=ubuntu@<BASTION_IP>'
monitoring_base_dir=/opt/monitoring

# observability 경로
config_render_mode=copy
prometheus_config_src=/opt/chilseongpa/observability/prometheus/prometheus.yml
grafana_datasource_src=/opt/chilseongpa/observability/grafana/datasource.yml
grafana_dashboard_provider_src=/opt/chilseongpa/observability/grafana/dashboard.yml

alertmanager_config_src=alertmanager.yml.j2
alert_rules_src=alert.rules.yml.j2