[monitoring]
localhost ansible_connection=local ansible_user=root

[monitoring:vars]
storage_setup_enabled=false
ansible_python_interpreter=/usr/bin/python3
# Monitoring Stack 설정 파일 및 docker-compose 위치
monitoring_base_dir=/workspace/.monitoring

# observability 설정 파일
config_render_mode=template
prometheus_config_src=prometheus.yml.j2
grafana_datasource_src=datasource.yml.j2
grafana_dashboard_provider_src=dashboard.yml.j2

alertmanager_config_src=alertmanager.yml.j2
alert_rules_src=alert.rules.yml.j2