[gcp_primary]
gcp-main ansible_host=34.50.46.56 tunnel_token=eyJhIjoiYzg1YTI4NDJiY2M0NDZlMmE2NmY2Y2ZkODk4MjU3OTAiLCJ0IjoiZDI0YmRmOTQtODdkMC00OGJhLTg0ODUtOTZkZWU1YzEwOGIzIiwicyI6IllYWnJkMDVqTkU5a1UzcFhkWGxtUmpCNFdYTjVTR05SWWpSNVNGQlBZVTQ9In0= db_conn=chilseongpa:asia-northeast3:hybrid-primary-db

[aws_bastion]
aws-bastion ansible_host=52.78.239.203

[aws_nodes]
aws-sub ansible_host=10.20.2.69 tunnel_token=eyJhIjoiYzg1YTI4NDJiY2M0NDZlMmE2NmY2Y2ZkODk4MjU3OTAiLCJ0IjoiZjQ0MWE4ZWUtZTczYi00NDY1LThjNDAtM2M4MGNiYjFkM2RhIiwicyI6IlJsZHhSbTlMU2pGNVYzcFJkMEpuVkRod1V6RkdZVXRUYWtGNmJuWnZOMDQ9In0=
aws-monitor ansible_host=10.20.2.83 tunnel_token=eyJhIjoiYzg1YTI4NDJiY2M0NDZlMmE2NmY2Y2ZkODk4MjU3OTAiLCJ0IjoiNDM2ZjkwNTEtMDA0MS00YWE3LTk3N2UtNDUzMTIxYWU1ZDZiIiwicyI6ImJrWjZSV3BCZURacVprUnFXV0o2WldSalVERkdUek5xZWtKMmRUQm5OWEk9In0=

# --- 그룹별 변수 설정 ---

[gcp_primary:vars]
# 앤서블 실행 위치(infra/ansible) 기준 두 단계 위
ansible_ssh_private_key_file=../../my_gcp_key

[aws_bastion:vars]
ansible_ssh_private_key_file=../../chilseongpa_keypair.pem

[aws_nodes:vars]
ansible_ssh_private_key_file=../../chilseongpa_keypair.pem
# 💡 핵심: Monitoring 등 내부망 서버 접속을 위해 Bastion을 징검다리로 사용
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@52.78.239.203 -i ../../chilseongpa_keypair.pem -o StrictHostKeyChecking=no"'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=ubuntu  
gcp_project_id=chilseongpa 
cf_client_id=632d5271991988851c910610ef555d2e.access
cf_client_secret=251a9ff6d8bd78ff02f3db2d360731015953d7a364d1d494294e0f5fdfd9f5d6
aws_ip=10.20.2.69
gcp_ip=34.50.46.56
app_domain=app.bucheongoyangijanggun.com
grafana_domain=grafana.bucheongoyangijanggun.com
prometheus_domain=prometheus.bucheongoyangijanggun.com
db_instance_name=chilseongpa:asia-northeast3:hybrid-primary-db

#db_conn 과 db_instance_name 은 전자의 경우 gcp 측에서 사용하는 변수명, db_instance_name 의 경우 aws_monitoring에서 사용하는 변수명