[gcp_primary]
gcp-main ansible_host=34.64.249.194 tunnel_token=eyJhIjoiYzg1YTI4NDJiY2M0NDZlMmE2NmY2Y2ZkODk4MjU3OTAiLCJ0IjoiYmQ1MTk0ZjAtMjY4Yi00YWEzLTk0NmMtMDJiNjZiMzQyMzFlIiwicyI6IldVSXpRakJJWlU0M04zbzJhalZLYWtGbGF6TnRZV2xrYkc1VWNtdDBRVk09In0= db_conn=chilseongpa:asia-northeast3:hybrid-primary-db

[aws_bastion]
aws-bastion ansible_host=3.35.206.107

[aws_nodes]
aws-sub ansible_host=10.20.2.247 tunnel_token=eyJhIjoiYzg1YTI4NDJiY2M0NDZlMmE2NmY2Y2ZkODk4MjU3OTAiLCJ0IjoiOTM5NGYxZDItOTA0OS00ZDk1LThhMmMtZjU2ZjM1N2IzZjBlIiwicyI6ImNHRXdZVGx0ZDBSWVkzaDFXR3N6VjFoblRrVlhSemw0VDFCeWNIWjNSelE9In0=
aws-monitor ansible_host=10.20.2.51 tunnel_token=eyJhIjoiYzg1YTI4NDJiY2M0NDZlMmE2NmY2Y2ZkODk4MjU3OTAiLCJ0IjoiOWM2NDljNTMtMzRhNC00NTRiLWE3YjQtY2ZlN2E2MmIxMTc5IiwicyI6ImNGbFBUV2x5U1VwVlNtOTVOR1JyTlZsTk9HOW9iblIwTmtjeGVqZHNUMlU9In0=

# --- 그룹별 변수 설정 ---

[gcp_primary:vars]
# 앤서블 실행 위치(infra/ansible) 기준 두 단계 위
ansible_ssh_private_key_file=../../my_gcp_key

[aws_bastion:vars]
ansible_ssh_private_key_file=../../chilseongpa_keypair.pem

[aws_nodes:vars]
ansible_ssh_private_key_file=../../chilseongpa_keypair.pem
# 💡 핵심: Monitoring 등 내부망 서버 접속을 위해 Bastion을 징검다리로 사용
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@3.35.206.107 -i ../../chilseongpa_keypair.pem -o StrictHostKeyChecking=no"'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=ubuntu  
gcp_project_id=chilseongpa 
cf_client_id=4a5c0af9d10122379a8ce7ac4305fb2d.access
cf_client_secret=7ce5d9f92b7b1b48caf1140e64b7b659bfd6ac5f25bf836117513bc3a7ee067b
aws_ip=10.20.2.247
gcp_ip=34.64.249.194
app_domain=app.bucheongoyangijanggun.com
grafana_domain=grafana.bucheongoyangijanggun.com
prometheus_domain=prometheus.bucheongoyangijanggun.com
db_instance_name=chilseongpa:asia-northeast3:hybrid-primary-db

#db_conn 과 db_instance_name 은 전자의 경우 gcp 측에서 사용하는 변수명, db_instance_name 의 경우 aws_monitoring에서 사용하는 변수명