[gcp_primary]
gcp-main ansible_host=34.158.201.111 tunnel_token=eyJhIjoiYzg1YTI4NDJiY2M0NDZlMmE2NmY2Y2ZkODk4MjU3OTAiLCJ0IjoiZGU2ZWEzMGEtMjM2Ni00ZTAwLTgyNTAtNzllMzZlMWJhNThmIiwicyI6IlVHSnJSbnBtWjFGTmJ6Sk5SRzlIWWpScWFscHZPRXBEVDBvNFNXeFBkbXM9In0= db_conn=chilseongpa:asia-northeast3:hybrid-primary-db

[gcp_monitoring]
gcp-monitor ansible_host=34.64.73.91 tunnel_token=eyJhIjoiYzg1YTI4NDJiY2M0NDZlMmE2NmY2Y2ZkODk4MjU3OTAiLCJ0IjoiN2I0OTFjNTQtMzQyZS00MTk5LThjYjUtZWU3MGM5NjE2MmUwIiwicyI6IlZ6UlpaMWxyTlVaalpHUmtSMWxDYVdKU2EwMXZhMWRKUjA1NVptVm9hakU9In0=

[aws_bastion]
aws-bastion ansible_host=43.201.53.215

[aws_nodes]
aws-sub ansible_host=10.20.2.199 tunnel_token=eyJhIjoiYzg1YTI4NDJiY2M0NDZlMmE2NmY2Y2ZkODk4MjU3OTAiLCJ0IjoiMGFjNjAxNjYtZmFjMi00YTRkLTllYzEtZjFmOTY1MTk3Mjg0IiwicyI6Ik1HUXdVR3M0WmpOUk9XaFFhR3gxYkU0MFdWcHBUVzF6VjBwME1WaEJiM009In0=

# --- 그룹별 변수 설정 ---

[gcp_primary:vars]
ansible_ssh_private_key_file=../../my_gcp_key

[gcp_monitoring:vars]
ansible_ssh_private_key_file=../../my_gcp_key
storage_setup_enabled=false

[aws_bastion:vars]
ansible_ssh_private_key_file=../../chilseongpa_keypair.pem

[aws_nodes:vars]
ansible_ssh_private_key_file=../../chilseongpa_keypair.pem
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@43.201.53.215 -i ../../chilseongpa_keypair.pem -o StrictHostKeyChecking=no"'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=ubuntu
gcp_project_id=chilseongpa
cf_client_id=c7c500c5acecc3fe0de739562e3348f3.access
cf_client_secret=f9683c4d8ec19fa042776897d98385277b98e78a1b93d253042e7bfca94bed8f
aws_ip=10.20.2.199
gcp_ip=34.158.201.111
gcp_internal_ip=10.30.0.2
app_domain=app.bucheongoyangijanggun.com
grafana_domain=grafana.bucheongoyangijanggun.com
prometheus_domain=prometheus.bucheongoyangijanggun.com
db_instance_name=chilseongpa:asia-northeast3:hybrid-primary-db
