---
# 공통 변수
project_name: "chilseongpa"
node_exporter_version: "1.7.0"
alert_webhook_url: "{{ lookup('env', 'ALERT_WEBHOOK_URL') }}" # Discord Webhook URL - 나중에 넣어줘야함
cf_client_id: "{{ lookup('env', 'CF_CLIENT_ID') }}"           # Cloudflare Access Client ID
cf_client_secret: "{{ lookup('env', 'CF_CLIENT_SECRET') }}"   # Cloudflare Access Client Secret
ebs_device_name: "/dev/xvdf"                                  # EBS 장치명 기본값
